const ADD_CHARACTER = "ADD_CHARACTER"
const ADD_CHARACTERS = "ADD_CHARACTERS"
const DELETE_CHARACTER = "DELETE_CHARACTER"
const ADD_SPELL = "ADD_SPELL"
const DELETE_SPELL = "DELETE_SPELL"
const ADD_ATTACK = "ADD_ATTACK"
const DELETE_ATTACK = "DELETE_ATTACK"
const ADD_EQUIPMENT = "ADD_EQUIPMENT"
const DELETE_EQUIPMENT = "DELETE_EQUIPMENT"
const UPDATE_CHARACTER = "UPDATE_CHARACTER"

export {
    ADD_CHARACTER,
    ADD_CHARACTERS,
    DELETE_CHARACTER,
    ADD_SPELL,
    DELETE_SPELL,
    ADD_ATTACK,
    DELETE_ATTACK,
    ADD_EQUIPMENT,
    DELETE_EQUIPMENT,
    UPDATE_CHARACTER,
}