const ADD_CHARACTER = "ADD_CHARACTER"
const DELETE_CHARACTER = "DELETE_CHARACTER"
const ADD_SPELL = "ADD_SPELL"
const DELETE_SPELL = "DELETE_SPELL"
const ADD_ATTACK = "ADD_ATTACK"
const DELETE_ATTACK = "DELETE_ATTACK"
const ADD_EQUIPMENT = "ADD_EQUIPMENT"
const DELETE_EQUIPMENT = "DELETE_EQUIPMENT"
const REQUESTING_CHARACTER_CHANGE = "REQUESTING_CHARACTER_CHANGE"
const REQUESTING_ATTACK_CHANGE = "REQUESTING_ATTACK_CHANGE"
const REQUESTING_EQUIPMENT_CHANGE = "REQUESTING_EQUIPMENT_CHANGE"
const REQUESTING_SPELL_CHANGE = "REQUESTING_SPELL_CHANGE"

export {
    ADD_CHARACTER,
    DELETE_CHARACTER,
    ADD_SPELL,
    DELETE_SPELL,
    ADD_ATTACK,
    DELETE_ATTACK,
    ADD_EQUIPMENT,
    DELETE_EQUIPMENT,
    REQUESTING_CHARACTER_CHANGE,
    REQUESTING_ATTACK_CHANGE,
    REQUESTING_EQUIPMENT_CHANGE,
    REQUESTING_SPELL_CHANGE
}