const ADD_CHARACTER = "ADD_CHARACTER"
const DELETE_CHARACTER = "DELETE_CHARACTER"
const ADD_SPELL = "ADD_SPELL"
const DELETE_SPELL = "DELETE_SPELL"
const ADD_ATTACK = "ADD_ATTACK"
const DELETE_ATTACK = "DELETE_ATTACK"


export {
    ADD_CHARACTER,
    DELETE_CHARACTER,
    ADD_SPELL,
    DELETE_SPELL,
    ADD_ATTACK,
    DELETE_ATTACK
}